version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbPagamentos
    volumes:
      - ./pgdata:/var/lib/postgresql/data2
    ports:
      - "5432:5432" #Porta usada:porta exposta para outros containers